[general]
live_config_reload = true

[colors.bright]
black = "0xff262b"
blue = "0x7dc6bf"
cyan = "0x35434d"
green = "0xc3e88d"
magenta = "0x6c71c4"
red = "0xeb606b"
white = "0xffffff"
yellow = "0xf7eb95"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "0x666666"
blue = "0x80cbc4"
cyan = "0xaeddff"
green = "0xc3e88d"
magenta = "0xff2f90"
red = "0xeb606b"
white = "0xffffff"
yellow = "0xf7eb95"

[colors.primary]
background = "0x1e282d"
foreground = "0xc4c7d1"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 11

[font.normal]
family = "JetbrainsMonoNL"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[terminal]
shell = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 0.8

[window.padding]
x = 20
y = 20

[cursor.style]
shape = "Beam"
