execute pathogen#infect()
filetype plugin on
filetype plugin indent on

filetype on
syntax on
colorscheme seagrey-dark

set colorcolumn=90

set number

set hidden
set history=100

filetype indent on
set nowrap
set expandtab
set smartindent
set autoindent

set showmatch
set hlsearch
