# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_BASE=~/.fzf

ZSH_THEME="pmcgee"

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
plugins=(sudo)

source $ZSH/oh-my-zsh.sh

ENABLE_CORRECTION="true"

export LC_ALL=en_US.UTF-8
export PAGER=most


# History

HISTFILE=~/.zsh_history
HISTSIZE=42000
SAVEHIST=42000

setopt append_history           # append
setopt extended_history         # store command timestamp and duration
setopt hist_ignore_all_dups     # no duplicate
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, dont wait until shell exit
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword
unsetopt hist_ignore_space      # ignore space prefixed commands

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nano'
else
  export EDITOR='subl'
fi

# Prompt
autoload -U promptinit
promptinit

# Completion
autoload -U compinit
compinit

setopt hash_list_all            # hash everything before completion
setopt always_to_end            # when completing from the middle of a word, move the cursor to the end of the word
setopt complete_in_word         # allow completion from within a word/phrase
setopt correct                  # spelling correction for commands
setopt correct_all              # try to correct spelling of commands
setopt auto_list                # automatically list choices on ambiguous completion
setopt list_packed              # pack columns
unsetopt list_ambiguous         # show completion when is command ambiguous

# Zshrc options
setopt auto_cd                  # if command is a path, cd into it
setopt chase_links              # resolve symlinks
setopt hist_ignore_space        # remove command lines from history if first character on the line is a space
setopt hash_list_all            # hash everything before completion
setopt always_to_end            # when completing from the middle of a word, move the cursor to the end of the word
setopt complete_in_word         # allow completion from within a word/phrase
setopt correct                  # spelling correction for commands
setopt correct_all              # try to correct spelling of commands
setopt auto_list                # automatically list choices on ambiguous completion
setopt list_packed              # pack columns
unsetopt list_ambiguous         # show completion when is command ambiguous
unsetopt menu_complete          # do not autoselect the first completion entry.
unsetopt complete_aliases       # complete alisases

# Aliases
source ~/.dotfiles/zshrc/zshrc.aliases
source ~/.dotfiles/zshrc/zshrc.aliases.archlinux
#source ~/.dotfiles/zshrc/zshrc.aliases.ubuntu

# Local
source $XDG_CONFIG_HOME/zsh/.zshrc.local
source $XDG_CONFIG_HOME/zsh/functions.sh

# EXPORTS
export PATH=$HOME/.local/bin:$PATH

# Webstorm
export PATH=$HOME/WebStorm-221.5787.30/bin:$PATH

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export PATH=$PATH:/opt/gradle/gradle-5.3/bin
export JAVA_HOME=/opt/jdk-18
# Maven
export PATH=$PATH:$HOME/apache-maven-3.6.3/bin
export PATH=$PATH:$JAVA_HOME/bin

# android
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# flutter
export PATH=$PATH:$HOME/flutter/bin
export PATH=$PATH:$HOME/flutter

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# ROFI
export PATH=$HOME/.config/rofi/bin:$PATH

#Fly.io
export FLYCTL_INSTALL="/home/vio/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

# opam configuration for OCAML
test -r /home/vio/.opam/opam-init/init.zsh && . /home/vio/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
systemctl --user import-environment SSH_AUTH_SOCK

# Mc Fly
eval "$(mcfly init zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/vio/google-cloud-sdk/path.zsh.inc' ]; then . '/home/vio/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/vio/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/vio/google-cloud-sdk/completion.zsh.inc'; fi

# pnpm
export PNPM_HOME="/home/vio/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export PATH=$HOME/.koyeb/bin:$PATH
export PATH=$HOME/.local/share/applications/cloud-sql-proxy:$PATH

export LS_COLORS="$(vivid generate molokai)"
