# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="bopzor"

# Plugins
plugins=(sudo colored-man-pages colorize httpie wd zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

ENABLE_CORRECTION="true"

export LC_ALL=en_US.UTF-8
export PAGER=most

# History
HISTFILE=~/.zsh_history
HISTSIZE=42000
SAVEHIST=42000

setopt append_history           # append
setopt extended_history         # store command timestamp and duration
setopt hist_ignore_all_dups     # no duplicate
setopt hist_reduce_blanks       # trim blanks
setopt hist_verify              # show before executing history commands
setopt inc_append_history       # add commands as they are typed, dont wait until shell exit
setopt share_history            # share hist between sessions
setopt bang_hist                # !keyword
unsetopt hist_ignore_space      # ignore space prefixed commands

# Prompt
autoload -U promptinit
promptinit

# Completion
autoload -U compinit
compinit

# Zsh options
setopt auto_cd                  # if command is a path, cd into it
setopt chase_links              # resolve symlinks
setopt hist_ignore_space        # remove command lines from history if first character on the line is a space
setopt hash_list_all            # hash everything before completion
setopt always_to_end            # when completing from the middle of a word, move the cursor to the end of the word
setopt complete_in_word         # allow completion from within a word/phrase
setopt correct                  # spelling correction for commands
setopt correct_all              # try to correct spelling of commands
setopt auto_list                # automatically list choices on ambiguous completion
setopt list_packed              # pack columns
unsetopt list_ambiguous         # show completion when is command ambiguous
unsetopt menu_complete          # do not autoselect the first completion entry.
unsetopt complete_aliases       # complete alisases

# Aliases
source ~/.dotfiles/zshrc/zshrc.aliases
source ~/.dotfiles/zshrc/zshrc.aliases.archlinux
#source ~/.dotfiles/zshrc/zshrc.aliases.ubuntu

# Local
source $XDG_CONFIG_HOME/zsh/.zshrc.local
source $XDG_CONFIG_HOME/zsh/functions.sh

# EXPORTS
export PATH=$HOME/.local/bin:$PATH

# NVM
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
systemctl --user import-environment SSH_AUTH_SOCK

# pnpm
export PNPM_HOME="/home/vio/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export PATH=$HOME/.koyeb/bin:$PATH

export LS_COLORS="$(vivid generate rose-pine)"

# Android
export ANDROID_HOME=/opt/android-sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin
